export enum ActionTypes {
  CHANGE_SELECTED_DATES_DATA = "CHANGE_SELECTED_DATES_DATA",
  CHANGE_PATH = "CHANGE_PATH",
  BLOCK_LIST = "BLOCK_LIST",
  FRAUD_SCORE_LIST = "FRAUD_SCORE_LIST",
  CUSTOMERS_LIST = "CUSTOMERS_LIST",
  QUEUES_LIST = "QUEUES_LIST",
  QUEUES_SESSION_LIST = "QUEUES_SESSION_LIST",
}
