/* this file is auto-generated, DO NOT EDIT MANUALLY */

export const EmailReasonCodes: { [key: string]: string } = {
  DLR: "domain low risk",
  DVC: "domain very high risk",
  DVI: "domain very high risk for your industry",
  DVN: "domain very high risk across entire network",
  DHR: "domain high risk",
  DHI: "domain high risk for your industry",
  DHN: "domain high risk for across entire network",
  DRD: "risky domain",
  DRR: "risky domain",
  DRC: "Domains are grouped into broad categories, like banking, webmail, etc. Categories with high fraud rates will become 'High Risk Categories'.",
  DDN: "domain does not exist in our partner's registry (note domain might still have valid DNS record)",
  DLC: "domain low risk category",
  DHC: "domain high risk category",
  DNC: "newly created email domain",
  DCO: "domain country is considered as risky",
  DMR: "domain moderate risk",
  EFO: "email was marked as fraudulent via you or any other sardine customers",
  EF3: "across our partner network, 3 or more customers identified email as fraud",
  EF2: "across our partner network, 2 customers identified email as fraud",
  EF1: "across our partner network, 1 customer identified email as fraud",
  EAW: "email created last week",
  EAM: "email created last month",
  EA4: "email created last four month",
  EHR: "Email has high probability of being associated to fraud due to multiple risk factors",
  EG1: "across our partner network, 1 customer identified email as good",
  EG2: "across our partner network, 2 customers identified email as good",
  EG3: "across our partner network, 3 customers identified email as good",
  EG4: "across our partner network, 4 customers identified email as good",
  EG5: "across our partner network, 5 customers identified email as good",
  EG6: "across our partner network, 6 or more customers identified email as good",
  ESF: "Email was marked as Fraud with the 'Suspected Fraud' type",
  EMF: "Email was marked as Fraud with the 'Suspected Fraud' type multiple times",
  EIS: "email invalid syntax",
  EDN: "email does not exist",
  EEC: "multiple email addresses with similar handle patterns were recently queried by you or other companies within sardine network",
  EEI: "multiple email addresses with similar handle patterns were recently queried by other companies",
  ETA: "Different variation of the email which points to the same inbox was recently queried. For instance, if a.bc@gmail.com was queried before, then ab.c@gmail.com will be considered as tumbled.",
  EV3: "across our partner network, 3 customers queried the same email in short amount of time",
  EV4: "across our partner network, 4 customers queried the same email in short amount of time",
  EVH: "across our partner network, more than 4 customers queried the same email in short amount of time",
  ELL: "email linked to low-risk linkedin account",
  ELT: "email linked to low-risk twitter account",
  ELS: "email linked to low-risk social media account",
  EA6: "email created last 6 month",
  ENN: "Email address handle contains numeric email patterns",
  ERS: "email patterns that have been found to be associated to fraud",
  EFB: "email owner has exceeded allowable capacity of email service",
  EMI: "email address is no longer active",
  EME: "email address existed in the past and is no longer available",
  EAY: "email created last year",
  E2Y: "email created last two year",
  ESY: "email first seen at least one year ago",
  E4Y: "email created more than 4 years ago",
  ES4: "email seen at least four years ago",
  ENP: "email not provided",
  ELH: "not enough relevant information to determine fraud risk",
  EDP: "Disposable email domain",
  EDI: "Invalid email domain",
};

export const BankReasonCodes: { [key: string]: string } = {
  BAC: "account reported closed",
  BIR: "invalid routing number",
  BIA: "invalid or suspicious account number",
  DIV: "invalid driver license format",
  CTL: "check sequence number is too low",
  OMD: "dollar amount exceeded max",
  DMI: "driver license is required but missing",
  PMS: "phone number is required but missing",
  DBI: "duplicate bank info processed",
  ANS: "account number format is suspicious",
  BHC: "history of account closed",
  BHI: "history of no acct/invalid acct",
  BHU: "history of unauthorized",
  BHE: "history of ineligible transaction",
  BH2: "history of returns. no current unpaid items",
  BUR: "account has unpaid returns",
  TWL: "transaction has been exceeded window limit",
  TDL: "transaction has been exceeded daily limit",
  OFA: "OFAC warning or error",
  BMT: "processing is this abled for merchant account",
  BBL: "blocklisted routing and account number",
  UPA: "customer has unpaid item(s) with at least one item reported as closed account, no account or invalid account number",
  UPT: "customer has unpaid item(s) with at least one item reported as reserved, auth revoked, not authorized or item ineligible",
  UPS: "customer has recent unpaid return item and the reason for return is suspicious",
  UPH: "customer has unpaid return item(s). Returns are not recent but the reason for the return is suspicious.",
  UPU: "customer has 1 known unpaid item, other history is positive.  Account is not known to be closed.",
  UPM: "customer has multiple unpaid items.  Account is not known to be closed.",
  PIV: "invalid telephone number",
  TEX: "transaction exceeded the limit",
  DTX: "duplicate transaction detected",
  HAC: "reported history of account closed",
  HNA: "reported history of no account in the last 12 months",
  HIA: "reported history of invalid account number in the last 12 months",
  HRS: "reported history of reserved in the last 12 months",
  HAR: "reported history of authorization revoked in the last 12 months",
  NAH: "reported history of not authorized in the last 12 months",
  HCN: "reported history of corporate - not authorized in the last 12 months",
  HII: "reported history of item ineligible in the last 12 months",
  BHR: "history of returns.",
  NDD: "possible NON DDA account",
  CNU: "customer has no unpaid returns. account is not known to be closed",
  CRP: "customer has recently paid an  item and is no longer has an unpaid debt in the database",
  CLH: "Customer has no unpaid items with limited positive history",
  CSH: "Customer has no unpaid items with strong positive history",
  TMB: "Too many bank accounts are connected",
  NEB: "Not enough balance for transfer",
  PNR: "Previous NSF Returns History",
  VER: "Processing Error",
  V59: "Known debt within 60days",
  V61: "Known debt more than 60 days ago",
  VMU: "Customer has a multiple debts history due to NSF or hold on funds",
  VDT: "Customer has a debt history due to NSF or hold on funds",
  VDP: "Customer has a debt history due to NSF or hold on funds but otherwise account has positive history",
  VNO: "No history in database",
  VPD: "customer has recently paid off debt",
  VLH: "customer has limited positive history (less than 45 days and limited volume)",
  VPH: "positive history",
  VSH: "strong positive history",
  VSR: "strong positive recent history",
};

export const PhoneReasonCodes: { [key: string]: string } = {
  PAC: "Normalized address was used to complete empty address fields prior to match",
  PAU: "Address Undeliverable",
  PBA: "Business Address",
  PBL: "Mobile Business Line*",
  PCN: "First and Last name combined in one field",
  PCU: "Carrier call was unsuccessful.",
  PDA: "Dual address (Ex: 123 Main St PO Box 99)",
  PDI: "Death Indicator found on data",
  PDR: "The Device date returned was not obtained real-time, there could be a more recent Device change.",
  PDT: "Data retrieval timeout (verify API only)",
  PDV: "High device change velocity",
  PFN: "Family name found and used in matching",
  PGL: "Mobile Government Line*",
  PHR: "High-rise; address contains apartment or building sub-units",
  PHV: "High velocity of change events associated with phone",
  PIA: 'Inactive address (Examples: New developments may have addresses but will be "inactive" until somebody moves in. Or, after Hurricane Katrina, addresses in the affected area were marked as inactive for a time.)',
  PIN: "International phone number",
  PLA: "Low Tenure Address",
  PLM: "Line type match not met",
  PLP: "Low Tenure Device",
  PLS: "Low Tenure SIM",
  PLT: "Low Tenure Identity",
  PMA: "Address in the request associated with multiple active addresses",
  PMI: "Military address",
  PMV: "Maximum match value not met",
  PNA: "Address is valid and has been normalized prior to calculating the match score.",
  PNC: "Name & Address information is not available",
  PND: "Network Status information is not available",
  PNM: "Not a mobile line type",
  PNN: "Nick name found and used in matching. For example Bill matches with William.",
  PNO: "Newer Phone Ownership. Input identity has verified. A newer ownership (Identity) has been recently associated to the phone number.",
  PNP: "Non personal line",
  PNS: "Names were swapped (first/last)",
  PNU: "Phone number has been updated",
  PNV: "Phone number not valid",
  POD: "The ownership of the phone number was found prior to a disconnect date.",
  POL: "How long the identity has been associated to a phone number. Long Tenure > 90 days.",
  POO: 'Input identity has been verified. The ownership associated to this phone number has not been seen recently, however there is no known newer ownership. Aka the ownership is "older".',
  POS: "How long the identity has been associated to a phone number. Short Tenure between 8 and 90 days.",
  POU: "The date attributes associated to the phone number is not available. Ownership Tenure is Unknown.",
  POV: "How long the identity has been associated to a phone number. Very Short < 7 days.",
  PP3: "Postal code submitted matched first 3 digits",
  PP5: "Postal code submitted matched first 5 digits",
  PP9: "Postal code submitted matched first 9 digits",
  PPM: "Address associated with a Private Mailbox operator (Ex: UPS Store)",
  PPN: "Mobile Phone number is not active*",
  PPO: "Address is a PO Box",
  PPT: "Phone Number is currently in a ported state. Any number not currently on its original home carrier will have a PT reason code. This is NOT indicative of a recent carrier port.",
  PPV: "A successful person search verification was run.",
  PR1: "The number of identities associated to the phone number has exceeded Prove’s suggested limit. This could be an indication of a higher risk of fraudulent activity.",
  PRA: "Raw Address matched better than normalized Address",
  PRL: "Phone Number is associated with a high-risk linetype (Non-Fixed VoIP or Prepaid MVNO)*",
  PRM: "Matching used only Raw data",
  PRN: "Phone number is at a low risk for fraud as a mobile line listed on the Override Services Registry (OSR).",
  PRR: "Phone number is at a higher risk for fraud as a non-mobile line listed on the Override Services Registry (OSR).",
  PS1: "Synthetic identity reason code one – the person identity matched has multiple unique SSNs. This can indicate a higher risk of the identity being synthetic.",
  PS2: "Synthetic identity reason code two – the person identity matched has multiple DOB records. This can indicate a higher risk of the identity being synthetic.",
  PS3: "Synthetic identity reason code three – the person identity matched has a high number of relatives with the same/similar name. This may indicate the identity is synthetic.",
  PSA: "Sub-account line*",
  PSR: "The SIM date returned was not obtained real-time, there could be a more recent SIM change.",
  PTF: "Toll free area code",
  PUC: "Insufficient data to calculate trustScore",
  PUV: "Unable to verify address",
  PVA: "Address is vacant (unoccupied in the past 90 days)",
  PXD: "No driver's license data available to match to submitted driver's license parameters",
  TAA: "low activity",
  TAB: "low regular activity",
  TAC: "regular activity",
  TAD: "low-risk irregular activity",
  TAE: "medium-risk irregular activity",
  TAF: "high-risk irregular activity",
  TAG: "irregular number type",
  TBA: "no long-term activity",
  TBB: "high long-term activity",
  TBC: "high short-term activity",
  TBD: "moderate long-term activity",
  TBE: "moderate short-term activity",
  TCA: "no range activity",
  TCB: "low range activity",
  TCC: "moderate short-term range activity",
  TCD: "moderate long-term range activity",
  TCE: "high short-term range activity",
  TCF: "high long-term range activity",
  TDA: "moderate activity on risky services",
  TDB: "high activity on risky services",
  TEA: "very low number of completed calls",
  TEB: "low number of completed calls",
  TEC: "regular number of completed calls",
  TED: "high number of completed calls",
  TFA: "no activity",
  TFB: "no long-term activity",
  TFC: "sparse long-term activity",
  TFD: "continuous long-term activity",
  TFE: "high short-term activity",
  TFF: "high long-term activity",
  TGA: "no range activity",
  TGB: "low range activity",
  TGC: "moderate-range activity",
  TGD: "high-range activity",
  TGE: "very high-range activity",
  THA: "regular call duration",
  THB: "irregular call duration",
  TIA: "number was recently unassigned",
  TIB: "activity towards high number of unassigned phone numbers",
  TIC: "activity coming from high number of different phone numbers",
  TID: "activity towards high number of different phone numbers",
  TIE: "activity coming from high number of risky countries",
  TIF: "activity towards high number of risky countries",
  TIG: "activity concentrated in short time intervals",
  TIH: "activity towards high number of premium numbers",
  TII: "activity coming from high number of tollfree numbers",
  TIJ: "machine-like activity",
  TIK: "call center-like activity",
  TIL: "low successful outgoing traffic",
  TIM: "low successful incoming traffic",
  TIN: "low successful outgoing and incoming traffic",
  TJA: "seen in the last 1 day",
  TJB: "seen in the last 7 days",
  TJC: "seen in the last 15 days",
  TJD: "seen in the last 1 month",
  TJE: "seen in the last 2 months",
  TJH: "seen in the last 3 months",
  TJI: "seen more than 3 months ago",
  TKA: "premium number",
  TKB: "VOIP number",
  TKC: "toll-free number",
  TKD: "invalid number",
  TKH: "payphone number",
  TKI: "voicemail number",
  TKJ: "pager number",
  TKK: "high-risk phone type",
  TKL: "high-risk carrier",
  TKM: "medium-risk carrier",
  TKN: "high-risk prefix",
  TKO: "phone too long",
  TKP: "blocklisted number",
  TKQ: "high-risk country",
  TKR: "technical number",
  TKS: "number used by application",
  TKT: "number allowlisted by customer",
  TLA: "moderate short-term activity",
  TLB: "moderate long-term activity",
  TLC: "moderate short-term activity on risky services",
  TLD: "moderate long-term activity on risky services",
  TLE: "high short-term activity",
  TLF: "high long-term activity",
  TLG: "high short-term activity on risky services",
  TLH: "high long-term activity on risky services",
};

export const BehaviorReasonCodes: { [key: string]: string } = {
  BBEK: "Expert Key usage detected",
  BBAF: "AutoFill detected in LTM (longterm-memory) Fields",
  BBCP: "Copy Paste detected in LTM fields",
  SCM: "Scam or social engineering",
};

export const IdentityReasonCodes: { [key: string]: string } = {
  INM: "Identity mismatch between Onboarding and Sardine’s ID data partners",
  BAM: "Identity mismatch between Onboarding and Sardine’s bank data partners",
  BPM: "Identity mismatch between Onboarding and Sardine’s bank data partners",
};

export const Document_VerificationReasonCodes: { [key: string]: string } = {
  DFG: "Document is forged",
  FMS: "Document mismatch with selfie",
  DIU: "Document information doesn't match with user-provided information",
  DEX: "Document is expired",
  SDC: "Low risk ID document verification result",
};

export const TaxIDReasonCodes: { [key: string]: string } = {
  AAL: "Whether the supplied name or SSN is nonsense. - Abuse Score - Less fraudy",
  ABL: "Whether the supplied SSN is a randomly issued SSN. - Abuse Score - Less fraudy",
  ACL: "Whether the supplied SSN might belong to another person not yet credit active - Abuse Score - Less fraudy",
  ADL: "Whether the supplied SSN aligns with the consumer's address history. - Abuse Score - Less fraudy",
  AEL: "Whether the supplied SSN aligns with the consumer's DOB. - Abuse Score - Less fraudy",
  AFL: "Whether the phone aligns with the consumer's history. - Abuse Score - Less fraudy",
  AGL: "Whether the consumer is tied to an ITIN. - Abuse Score - Less fraudy",
  AHL: "Whether any of the supplied information corresponds to a deceased individual. - Abuse Score - Less fraudy",
  AIL: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - Abuse Score - Less fraudy",
  AJL: "Whether the consumer is tied to addresses linked to synthetic fraud. - Abuse Score - Less fraudy",
  AKL: "The depth of the consumer's history with this information. - Abuse Score - Less fraudy",
  ALL: "How well the start time of the consumer's history aligns with the expected start time. - Abuse Score - Less fraudy",
  AML: "Whether the consumer is tied to fraud code records. - Abuse Score - Less fraudy",
  ANL: "Whether there is a better owner for the SSN. - Abuse Score - Less fraudy",
  AOL: "Whether the consumer appears to have a better SSN. - Abuse Score - Less fraudy",
  APL: "How well the supplied information matches Manifest records. - Abuse Score - Less fraudy",
  AQL: "Whether other applications in SentiLink's system match aspects of this application's information. - Abuse Score - Less fraudy",
  ARL: "Attributes of addresses that the consumer is tied to. - Abuse Score - Less fraudy",
  ASL: "Whether aspects of the supplied PII correspond to bankruptcies. - Abuse Score - Less fraudy",
  ATL: "Whether the consumer is tied to security freezes. - Abuse Score - Less fraudy",
  AUL: "Whether the SSN might belong to an associate. - Abuse Score - Less fraudy",
  AVL: "Whether the supplied phone number corresponds to a risky carrier or line type. - Abuse Score - Less fraudy",
  AWL: "Whether the email domain or structure of the handle are suspicious. - Abuse Score - Less fraudy",
  AAM: "Whether the supplied name or SSN is nonsense. - Abuse Score - More fraudy",
  ABM: "Whether the supplied SSN is a randomly issued SSN. - Abuse Score - More fraudy",
  ACM: "Whether the supplied SSN might belong to another person not yet credit active - Abuse Score - More fraudy",
  ADM: "Whether the supplied SSN aligns with the consumer's address history. - Abuse Score - More fraudy",
  AEM: "Whether the supplied SSN aligns with the consumer's DOB. - Abuse Score - More fraudy",
  AFM: "Whether the phone aligns with the consumer's history. - Abuse Score - More fraudy",
  AGM: "Whether the consumer is tied to an ITIN. - Abuse Score - More fraudy",
  AHM: "Whether any of the supplied information corresponds to a deceased individual. - Abuse Score - More fraudy",
  AIM: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - Abuse Score - More fraudy",
  AJM: "Whether the consumer is tied to addresses linked to synthetic fraud. - Abuse Score - More fraudy",
  AKM: "The depth of the consumer's history with this information. - Abuse Score - More fraudy",
  ALM: "How well the start time of the consumer's history aligns with the expected start time. - Abuse Score - More fraudy",
  AMM: "Whether the consumer is tied to fraud code records. - Abuse Score - More fraudy",
  ANM: "Whether there is a better owner for the SSN. - Abuse Score - More fraudy",
  AOM: "Whether the consumer appears to have a better SSN. - Abuse Score - More fraudy",
  APM: "How well the supplied information matches Manifest records. - Abuse Score - More fraudy",
  AQM: "Whether other applications in SentiLink's system match aspects of this application's information. - Abuse Score - More fraudy",
  ARM: "Attributes of addresses that the consumer is tied to. - Abuse Score - More fraudy",
  ASM: "Whether aspects of the supplied PII correspond to bankruptcies. - Abuse Score - More fraudy",
  ATM: "Whether the consumer is tied to security freezes. - Abuse Score - More fraudy",
  AUM: "Whether the SSN might belong to an associate. - Abuse Score - More fraudy",
  AVM: "Whether the supplied phone number corresponds to a risky carrier or line type. - Abuse Score - More fraudy",
  AWM: "Whether the email domain or structure of the handle are suspicious. - Abuse Score - More fraudy",
  FAL: "Whether the supplied name or SSN is nonsense. - First Party Score - Less fraudy",
  FBL: "Whether the supplied SSN is a randomly issued SSN. - First Party Score - Less fraudy",
  FCL: "Whether the supplied SSN might belong to another person not yet credit active - First Party Score - Less fraudy",
  FDL: "Whether the supplied SSN aligns with the consumer's address history. - First Party Score - Less fraudy",
  FEL: "Whether the supplied SSN aligns with the consumer's DOB. - First Party Score - Less fraudy",
  FFL: "Whether the phone aligns with the consumer's history. - First Party Score - Less fraudy",
  FGL: "Whether the consumer is tied to an ITIN. - First Party Score - Less fraudy",
  FHL: "Whether any of the supplied information corresponds to a deceased individual. - First Party Score - Less fraudy",
  FIL: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - First Party Score - Less fraudy",
  FJL: "Whether the consumer is tied to addresses linked to synthetic fraud. - First Party Score - Less fraudy",
  FKL: "The depth of the consumer's history with this information. - First Party Score - Less fraudy",
  FLL: "How well the start time of the consumer's history aligns with the expected start time. - First Party Score - Less fraudy",
  FML: "Whether the consumer is tied to fraud code records. - First Party Score - Less fraudy",
  FNL: "Whether there is a better owner for the SSN. - First Party Score - Less fraudy",
  FOL: "Whether the consumer appears to have a better SSN. - First Party Score - Less fraudy",
  FPL: "How well the supplied information matches Manifest records. - First Party Score - Less fraudy",
  FQL: "Whether other applications in SentiLink's system match aspects of this application's information. - First Party Score - Less fraudy",
  FRL: "Attributes of addresses that the consumer is tied to. - First Party Score - Less fraudy",
  FSL: "Whether aspects of the supplied PII correspond to bankruptcies. - First Party Score - Less fraudy",
  FTL: "Whether the consumer is tied to security freezes. - First Party Score - Less fraudy",
  FUL: "Whether the SSN might belong to an associate. - First Party Score - Less fraudy",
  FVL: "Whether the supplied phone number corresponds to a risky carrier or line type. - First Party Score - Less fraudy",
  FWL: "Whether the email domain or structure of the handle are suspicious. - First Party Score - Less fraudy",
  FAM: "Whether the supplied name or SSN is nonsense. - First Party Score - More fraudy",
  FBM: "Whether the supplied SSN is a randomly issued SSN. - First Party Score - More fraudy",
  FCM: "Whether the supplied SSN might belong to another person not yet credit active - First Party Score - More fraudy",
  FDM: "Whether the supplied SSN aligns with the consumer's address history. - First Party Score - More fraudy",
  FEM: "Whether the supplied SSN aligns with the consumer's DOB. - First Party Score - More fraudy",
  FFM: "Whether the phone aligns with the consumer's history. - First Party Score - More fraudy",
  FGM: "Whether the consumer is tied to an ITIN. - First Party Score - More fraudy",
  FHM: "Whether any of the supplied information corresponds to a deceased individual. - First Party Score - More fraudy",
  FIM: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - First Party Score - More fraudy",
  FJM: "Whether the consumer is tied to addresses linked to synthetic fraud. - First Party Score - More fraudy",
  FKM: "The depth of the consumer's history with this information. - First Party Score - More fraudy",
  FLM: "How well the start time of the consumer's history aligns with the expected start time. - First Party Score - More fraudy",
  FMM: "Whether the consumer is tied to fraud code records. - First Party Score - More fraudy",
  FNM: "Whether there is a better owner for the SSN. - First Party Score - More fraudy",
  FOM: "Whether the consumer appears to have a better SSN. - First Party Score - More fraudy",
  FPM: "How well the supplied information matches Manifest records. - First Party Score - More fraudy",
  FQM: "Whether other applications in SentiLink's system match aspects of this application's information. - First Party Score - More fraudy",
  FRM: "Attributes of addresses that the consumer is tied to. - First Party Score - More fraudy",
  FSM: "Whether aspects of the supplied PII correspond to bankruptcies. - First Party Score - More fraudy",
  FTM: "Whether the consumer is tied to security freezes. - First Party Score - More fraudy",
  FUM: "Whether the SSN might belong to an associate. - First Party Score - More fraudy",
  FVM: "Whether the supplied phone number corresponds to a risky carrier or line type. - First Party Score - More fraudy",
  FWM: "Whether the email domain or structure of the handle are suspicious. - First Party Score - More fraudy",
  TAL: "Whether the supplied name or SSN is nonsense. - Third Party Score  - Less fraudy",
  TBL: "Whether the supplied SSN is a randomly issued SSN. - Third Party Score  - Less fraudy",
  TCL: "Whether the supplied SSN might belong to another person not yet credit active - Third Party Score  - Less fraudy",
  STDL: "Whether the supplied SSN aligns with the consumer's address history. - Third Party Score  - Less fraudy",
  TEL: "Whether the supplied SSN aligns with the consumer's DOB. - Third Party Score  - Less fraudy",
  TFL: "Whether the phone aligns with the consumer's history. - Third Party Score  - Less fraudy",
  TGL: "Whether the consumer is tied to an ITIN. - Third Party Score  - Less fraudy",
  THL: "Whether any of the supplied information corresponds to a deceased individual. - Third Party Score  - Less fraudy",
  STIL: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - Third Party Score  - Less fraudy",
  TJL: "Whether the consumer is tied to addresses linked to synthetic fraud. - Third Party Score  - Less fraudy",
  STKL: "The depth of the consumer's history with this information. - Third Party Score  - Less fraudy",
  TLL: "How well the start time of the consumer's history aligns with the expected start time. - Third Party Score  - Less fraudy",
  TML: "Whether the consumer is tied to fraud code records. - Third Party Score  - Less fraudy",
  TNL: "Whether there is a better owner for the SSN. - Third Party Score  - Less fraudy",
  TOL: "Whether the consumer appears to have a better SSN. - Third Party Score  - Less fraudy",
  TPL: "How well the supplied information matches Manifest records. - Third Party Score  - Less fraudy",
  TQL: "Whether other applications in SentiLink's system match aspects of this application's information. - Third Party Score  - Less fraudy",
  TRL: "Attributes of addresses that the consumer is tied to. - Third Party Score  - Less fraudy",
  TSL: "Whether aspects of the supplied PII correspond to bankruptcies. - Third Party Score  - Less fraudy",
  TTL: "Whether the consumer is tied to security freezes. - Third Party Score  - Less fraudy",
  TUL: "Whether the SSN might belong to an associate. - Third Party Score  - Less fraudy",
  TVL: "Whether the supplied phone number corresponds to a risky carrier or line type. - Third Party Score  - Less fraudy",
  STWL: "Whether the email domain or structure of the handle are suspicious. - Third Party Score  - Less fraudy",
  TAM: "Whether the supplied name or SSN is nonsense. - Third Party Score  - More fraudy",
  TBM: "Whether the supplied SSN is a randomly issued SSN. - Third Party Score  - More fraudy",
  TCM: "Whether the supplied SSN might belong to another person not yet credit active - Third Party Score  - More fraudy",
  STDM: "Whether the supplied SSN aligns with the consumer's address history. - Third Party Score  - More fraudy",
  TEM: "Whether the supplied SSN aligns with the consumer's DOB. - Third Party Score  - More fraudy",
  TFM: "Whether the phone aligns with the consumer's history. - Third Party Score  - More fraudy",
  TGM: "Whether the consumer is tied to an ITIN. - Third Party Score  - More fraudy",
  THM: "Whether any of the supplied information corresponds to a deceased individual. - Third Party Score  - More fraudy",
  STIM: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - Third Party Score  - More fraudy",
  TJM: "Whether the consumer is tied to addresses linked to synthetic fraud. - Third Party Score  - More fraudy",
  STKM: "The depth of the consumer's history with this information. - Third Party Score  - More fraudy",
  TLM: "How well the start time of the consumer's history aligns with the expected start time. - Third Party Score  - More fraudy",
  TMM: "Whether the consumer is tied to fraud code records. - Third Party Score  - More fraudy",
  TNM: "Whether there is a better owner for the SSN. - Third Party Score  - More fraudy",
  TOM: "Whether the consumer appears to have a better SSN. - Third Party Score  - More fraudy",
  TPM: "How well the supplied information matches Manifest records. - Third Party Score  - More fraudy",
  TQM: "Whether other applications in SentiLink's system match aspects of this application's information. - Third Party Score  - More fraudy",
  TRM: "Attributes of addresses that the consumer is tied to. - Third Party Score  - More fraudy",
  TSM: "Whether aspects of the supplied PII correspond to bankruptcies. - Third Party Score  - More fraudy",
  TTM: "Whether the consumer is tied to security freezes. - Third Party Score  - More fraudy",
  TUM: "Whether the SSN might belong to an associate. - Third Party Score  - More fraudy",
  TVM: "Whether the supplied phone number corresponds to a risky carrier or line type. - Third Party Score  - More fraudy",
  STWM: "Whether the email domain or structure of the handle are suspicious. - Third Party Score  - More fraudy",
  IAL: "Whether the supplied name or SSN is nonsense. - ID theft score - Less fraudy",
  IHL: "Whether any of the supplied information corresponds to a deceased individual. - ID theft score - Less fraudy",
  IIL: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - ID theft score - Less fraudy",
  IML: "Whether the consumer is tied to fraud code records. - ID theft score - Less fraudy",
  IQL: "Whether other applications in SentiLink's system match aspects of this application's information. - ID theft score - Less fraudy",
  IVL: "Whether the supplied phone number corresponds to a risky carrier or line type. - ID theft score - Less fraudy",
  IWL: "Whether the email domain or structure of the handle are suspicious. - ID theft score - Less fraudy",
  IXL: "How consistent the address is with the consumer's history. - ID theft score - Less fraudy",
  IYL: "Whether the address has a high velocity of applications. - ID theft score - Less fraudy",
  IZL: "Whether the email has had suspicious application activity. - ID theft score - Less fraudy",
  IAAL: "Whether the applicant appears to be the best owner of the email. - ID theft score - Less fraudy",
  IABL: "Whether the application information contains a mix of information from different consumers. - ID theft score - Less fraudy",
  IACL: "Whether there is unusual geographic activity associated with the phone number. - ID theft score - Less fraudy",
  IADL: "Whether the applicant appears to be the best owner of the phone. - ID theft score - Less fraudy",
  IAEL: "The number of recent applications associated with the phone. - ID theft score - Less fraudy",
  IAFL: "Whether the application's IP address is from a risky VPN. - ID theft score - Less fraudy",
  IAGL: "Whether the IP address aligns with the applicant's physical address history. - ID theft score - Less fraudy",
  IAHL: "Whether the applicant has a suspicious gap in history. - ID theft score - Less fraudy",
  IAIL: "Length of history of the email. - ID theft score - Less fraudy",
  IAM: "Whether the supplied name or SSN is nonsense. - ID theft score - More fraudy",
  IHM: "Whether any of the supplied information corresponds to a deceased individual. - ID theft score - More fraudy",
  IIM: "Whether the SSN is tied to a clump of SSNs empirically used for fraud. - ID theft score - More fraudy",
  IMM: "Whether the consumer is tied to fraud code records. - ID theft score - More fraudy",
  IQM: "Whether other applications in SentiLink's system match aspects of this application's information. - ID theft score - More fraudy",
  IVM: "Whether the supplied phone number corresponds to a risky carrier or line type. - ID theft score - More fraudy",
  IWM: "Whether the email domain or structure of the handle are suspicious. - ID theft score - More fraudy",
  IXM: "How consistent the address is with the consumer's history. - ID theft score - More fraudy",
  IYM: "Whether the address has a high velocity of applications. - ID theft score - More fraudy",
  IZM: "Whether the email has had suspicious application activity. - ID theft score - More fraudy",
  IAAM: "Whether the applicant appears to be the best owner of the email. - ID theft score - More fraudy",
  IABM: "Whether the application information contains a mix of information from different consumers. - ID theft score - More fraudy",
  IACM: "Whether there is unusual geographic activity associated with the phone number. - ID theft score - More fraudy",
  IADM: "Whether the applicant appears to be the best owner of the phone. - ID theft score - More fraudy",
  IAEM: "The number of recent applications associated with the phone. - ID theft score - More fraudy",
  IAFM: "Whether the application's IP address is from a risky VPN. - ID theft score - More fraudy",
  IAGM: "Whether the IP address aligns with the applicant's physical address history. - ID theft score - More fraudy",
  IAHM: "Whether the applicant has a suspicious gap in history. - ID theft score - More fraudy",
  IAIM: "Length of history of the email. - ID theft score - More fraudy",
  SSF: "Subject has placed a security freeze on their SSN file",
  SDP: "Subject reported deceased",
  SFV: "Facta fraud victim initial alert. Active for 90 days",
  SFX: "Facta Fraud victim extended alert. Active for 7 years",
  SFQ: "Facta Active Duty Alert with Fraud victim - initial alert. Active for 90 days.",
  SFW: "Facta Active Duty Alert with Fraud victim. Active for 1 year",
  SFN: "Facta Active Duty alert. Active for one year",
};

export const CryptoAMLReasonCodes: { [key: string]: string } = {
  EXC: "This address has been tied to an exchange",
  CUS: "This address has been tied to a custodian",
  CATM: "This address has been tied to an atm",
  MER: "This address has been tied to a merchant",
  PROR: "This address has been tied to a processor",
  MARK: "This address has been tied to a market",
  SER: "This address has been tied to a service",
  WEB: "This address has been tied to a website",
  DON: "This address has been tied to a donation",
  FOR: "This address has been tied to a forum",
  USER: "This address has been tied to a username",
  PER: "This address has been tied to a person",
  AUC: "This address has been tied to a auction",
  LAW: "This address has been tied to law_enforcement",
  BURN: "This address has been tied to burning",
  ICO: "This address has been tied to ico",
  TOK: "This address has been tied to a token",
  EQY: "This address has been tied to a equity",
  SEC: "This address has been tied to security",
  UTY: "This address has been tied to utility",
  DAPP: "This address has been tied to dapp",
  GAME: "This address has been tied to gaming",
  MINE: "This address has been tied to a iner",
  POOL: "This address has been tied to a pool",
  FAUT: "This address has been tied to a faucet",
  FIAT: "This address has been tied to a fiat",
  KYC: "This address has been tied to kyc",
  NKYC: "This address has been tied to nokyc",
  GAMB: "This address has been tied to gambling",
  MIX: "This address has been tied to mixer",
  SCAM: "This address has been tied to a scam",
  THEF: "This address has been tied to a theft",
  RSOM: "This address has been tied to ransom",
  MALW: "This address has been tied to malware",
  ILGL: "This address has been tied to illegal",
  DARK: "This address has been tied to the darknet",
  TERR: "This address has been tied to terrorism",
  OFAC: "This address has been tied to the OFAC list",
  LAUN: "This address has been tied to money laundering",
};

export const AllowlistReasonCodes: { [key: string]: string } = {
  AEA: "Email is in allowlist",
  ADE: "Device is in allowlist",
  AUS: "User is in allowlist",
  ALW: "Session is given low risk because of allowlist",
};

export const AMLCatagoryCodeReasonCodes: { [key: string]: string } = {
  SABU: "Abuse (Domestic, Elder, Child)",
  SARS: "Arson",
  SAST: "Assault, Battery",
  SBLK: "Firm Specific Block List",
  SBRB: "Bribery, Graft, Kickbacks, Political Corruption",
  SBUR: "Burglary",
  SBUS: "Business Crimes (Antitrust, Bankruptcy, Price Fixing)",
  SCFT: "Counterfeiting, Forgery",
  SCON: "Conspiracy (No specific crime named)",
  SCPR: "Copyright Infringement (Intellectual Property, Electronic Piracy)",
  SCYB: "Computer Related, Cyber Crime",
  SDEN: "Denied Entity",
  SDPS: "Possession of Drugs or Drug Paraphernalia",
  SDTF: "Trafficking or Distribution of Drugs",
  SENV: "Environmental Crimes (Poaching, Illegal Logging, Animal Cruelty",
  SFAR: "Foreign Agent Registration Act",
  SFOF: "Former OFAC",
  SFOR: "Forfeiture",
  SFOS: "Former Sanctions List",
  SFRD: "Fraud, Scams, Swindles",
  SFUG: "Escape, Fugitive",
  SGAM: "Illegal Gambling",
  SHCD: "Health Care Disciplines",
  SHUM: "Human rights, Genocide, War crimes",
  SIGN: "Possession or Sale of Guns, Weapons and Explosives",
  SIMP: "Identity Theft, Impersonation",
  SIPR: "Illegal Prostitution, Promoting Illegal Prostitution",
  SIRC: "Iran Connect",
  SKID: "Kidnapping, Abduction, Held Against Will",
  SLMD: "Legal Marijuana Dispensary",
  SLNS: "Loan Sharking, Usury, Predatory Lending",
  SMIS: "Misconduct",
  SMLA: "Money Laundering",
  SMOR: "Mortgage Related",
  SMSB: "Money Services Business",
  SMUR: "Murder, Manslaughter (Committed, Planned or Attempted)",
  SNSC: "Non Specific Crime",
  SOBS: "Obscenity Related, Child Pornography",
  SORG: "Organized Crime, Criminal Association, Racketeering",
  SPEP: "Person Political",
  SPRJ: "False Filings, False Statements, Perjury, Obstruction of Justice",
  SPSP: "Possession of Stolen Property",
  SREG: "Regulatory Action",
  SRES: "Real Estate Actions",
  SROB: "Robbery (Stealing by Threat, Use of Force)",
  SSEC: "SEC Violations (Insider Trading, Securities Fraud)",
  SSEX: "Sex Offenses (Rape, Sodomy, Sexual Abuse, Pedophilia)",
  SSMG: "Smuggling (Does not include Drugs, Money, People or Guns)",
  SSNX: "Sanctions Connect",
  SSPY: "Espionage, Spying, Treason",
  STAX: "Tax Related Offenses",
  STER: "Terrorist Related",
  STFT: "Theft (Larceny, Misappropriation, Embezzlement, Extortion)",
  STRF: "People Trafficking, Organ Trafficking",
  SWLT: "Watch List",
};

export const AMLSubCatagoryCodeReasonCodes: { [key: string]: string } = {
  SACC: "Accuse",
  SACQ: "Acquit, Not Guilty",
  SACT: "Disciplinary, Regulatory Action",
  SADT: "Audit",
  SALL: "Allege",
  SAPL: "Appeal",
  SARB: "Arbitration",
  SARN: "Arraign",
  SART: "Arrest",
  SASC: "Associated with, Seen with",
  SCEN: "Censure",
  SCHG: "Charged",
  SCMP: "Complaint Filed",
  SCNF: "Confession",
  SCSP: "Conspire",
  SCVT: "Convict, Conviction",
  SDEP: "Deported",
  SDMS: "Dismissed",
  SEXP: "Expelled",
  SFIL: "Fine - Less than $10,000",
  SFIM: "Fine - More than $10,000",
  SGOV: "Government Official",
  SIND: "Indict, Indictment",
  SLIC: "Licensing Action",
  SLIN: "Lien",
  SPLE: "Plea",
  SPRB: "Probe",
  SRVK: "Revoked Registration",
  SSAN: "Sanction",
  SSET: "Settlement or Suit",
  SSEZ: "Seizure",
  SSJT: "Served Jail Time",
  SSPD: "Suspended",
  SSPT: "Suspected",
  STRL: "Trial",
  SWTD: "Wanted",
};

export const AllReasonCodes: { [key: string]: string } = {
  ...EmailReasonCodes,
  ...BankReasonCodes,
  ...PhoneReasonCodes,
  ...BehaviorReasonCodes,
  ...IdentityReasonCodes,
  ...Document_VerificationReasonCodes,
  ...TaxIDReasonCodes,
  ...CryptoAMLReasonCodes,
  ...AllowlistReasonCodes,
  ...AMLCatagoryCodeReasonCodes,
  ...AMLSubCatagoryCodeReasonCodes,
};
